# Generated by Django 5.2.11 on 2026-02-26 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0777_realm_branding'),
        ('zerver', '0782_delete_unused_anonymous_groups'),
    ]

    operations = [
    ]
